version: '3.9'

services:
  db:
    restart: always
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: simpleMessenger
      POSTGRES_DB: simpleMessenger
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    
  simplemessenger.api:
    build:
      context: ../scr/SimpleMessenger.Api
      dockerfile: Dockerfile
    depends_on:
      db:
       condition: service_started
    ports:
      - 8080:8080

  front:
    container_name: simplemessenger.frontend
    build:
      context: ..
      dockerfile: front/Dockerfile
    ports:
      - "3000:3000"